services:
  interactivefloor:
    image: ${DOCKER_REGISTRY-}interactivefloor
    build:
      context: .
      dockerfile: InteractiveFloor/Dockerfile
    ports:
      - 8080:8080
    restart: always
